### ISSUE TITLE
Cloud docs - clarification for a user applying device-specific permissions in role of sysadmin

### ISSUE THREAD

**Issue by chanerator** [ibm-cloud-docs/gateway-appliance#1]
URL REFERENCE

https://cloud.ibm.com/docs/gateway-appliance?topic=gateway-appliance-managing-permissions-and-device-access#adding-specific-device-level-permissions

TEXT REFERENCE:
Log in to the [Access (IAM)](https://cloud.ibm.com/iam/users) page in the IBM Cloud® console.
    Select View: My classic infrastructure users.
    Select a user, then click the Classic infrastructure tab and the Devices tab.
    In the Select type section, select All bare metal servers to allow users to access all the bare metal devices.
    In the Enable future access section, select Auto bare metal server access to grant the user permanent access to any newly added bare metal device.
    Use the devices table to grant a user access to specific, individual devices.
    Click Set.
*************

For above link, which relates to adding a device-specific permission, it would be helpful to state that in order for you to "see" specific devices, the user must ALREADY have some kind of device permission on the permissions tab.  If you skip that step, there will be no devices listed.

**Comment by jbmitch** [comment]
Fixed, please review and close
